### ISSUE TITLE
Scrum report #1

### ISSUE THREAD

**Issue by Landseer100** [ptellier/nimbase#1]
We can put out first scrum report here. I think it’s due at 10pm tonight @Aryan-B @ptellier

**Comment by jakemilad** [comment]
b2c3e

I've worked on planning what components we would need in the front end. In the next two weeks I'll be looking into authentication as well as implementing the initial template for the project. We might have got stuck on organizing ideal times for us to meet and discuss things as well as a team member who dropped the course.

**Comment by Landseer100** [comment]
A8j3b

I’ve been working how I am going to create the main gallery page and homepage. I have not used react before so I’m doing a lot of self study so I can replicate our teams designs. In the next two weeks I’ll be taking my learning and the designs and turning them into reality. We are still trying to find a 5th team mate as one person left which is a little hectic.

**Comment by ptellier** [comment]
Phillip Tellier:

In the last two weeks I wrote a lot of the requirements in the readme for our project and fleshed out a lot of the details of each section. I created rough sketches of the web pages and functionality, then created a custom SVG icon and wireframes for the whole site in Figma. It was hard to plan meetings and we do not seem to have a lot of free time in common, so we may have to stick to meeting before/after class and lab. In the next two weeks I am going to work on setting up the mongoDB database and helping out setting up the basic structure of the React front-end according to my wireframes.

**Comment by Aryan-B** [comment]
Bhairaw Aryan (k0i3b)

During the past iteration, I focused on project planning and research. I created a project workflow and constructed Miro diagrams for the DevOps section. I also researched GitHub Actions, pipelines, and how to set up Nginx reverse proxy manager for communication with Docker containers. For the upcoming two weeks, my plan is to set up GitHub Actions to pull code from the repository and build it locally. Additionally, I will create a sample project for testing purposes. If time allows, I will proceed with setting up the Docker containers. Challenges I faced included resolving CORS policy issues due to server setup requirements and handling an increased workload after a group member dropped the course.
